export {default as Nav} from "./Nav/Nav"
export {default as Footer} from "./Footer/Footer"
export {default as About} from "./About/About"
export {default as Contact} from "./Contact/Contact"
export {default as Home} from "./Home/Home"
export {default as Answer} from "./Answer/Answer"
export {default as Login} from "./Login/Login"